"""Add unique constraint to Bucket.name

Revision ID: d94bbc10fd92
Revises: f23eece2b534
Create Date: 2025-11-24 15:03:20.529264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94bbc10fd92'
down_revision = 'f23eece2b534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_buckets_name", ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.drop_constraint("uq_buckets_name", type_='unique')

    # ### end Alembic commands ###
